import { createColumnHelper } from "@tanstack/react-table";
import type { BattingStatRow } from "../interfaces/batting_stats";

const columnHelperProperties = {
    header: (info: any) => info.column.id.replace(/_/g, " ").toUpperCase(),
    footer: (info: any) => info.column.id.replace(/_/g, " ").toUpperCase(),
    cell: (info: any) => info.getValue(),
};
const columnHelper = createColumnHelper<BattingStatRow>();
export const battingColumns = {
    year: columnHelper.accessor("year", columnHelperProperties),
    player_id: columnHelper.accessor("player_id", columnHelperProperties),
    team: columnHelper.accessor("team", columnHelperProperties),
    month: columnHelper.accessor("month", columnHelperProperties),
    day: columnHelper.accessor("day", columnHelperProperties),
    game_id: columnHelper.accessor("game_id", columnHelperProperties),
    start_year: columnHelper.accessor("start_year", columnHelperProperties),
    end_year: columnHelper.accessor("end_year", columnHelperProperties),
    G: columnHelper.accessor("G", columnHelperProperties),
    PA: columnHelper.accessor("PA", columnHelperProperties),
    AB: columnHelper.accessor("AB", columnHelperProperties),
    H: columnHelper.accessor("H", columnHelperProperties),
    "1B": columnHelper.accessor("1B", columnHelperProperties),
    "2B": columnHelper.accessor("2B", columnHelperProperties),
    "3B": columnHelper.accessor("3B", columnHelperProperties),
    HR: columnHelper.accessor("HR", columnHelperProperties),
    UBB: columnHelper.accessor("UBB", columnHelperProperties),
    IBB: columnHelper.accessor("IBB", columnHelperProperties),
    HBP: columnHelper.accessor("HBP", columnHelperProperties),
    SF: columnHelper.accessor("SF", columnHelperProperties),
    SH: columnHelper.accessor("SH", columnHelperProperties),
    K: columnHelper.accessor("K", columnHelperProperties),
    DP: columnHelper.accessor("DP", columnHelperProperties),
    TP: columnHelper.accessor("TP", columnHelperProperties),
    ROE: columnHelper.accessor("ROE", columnHelperProperties),
    FC: columnHelper.accessor("FC", columnHelperProperties),
    R: columnHelper.accessor("R", columnHelperProperties),
    RBI: columnHelper.accessor("RBI", columnHelperProperties),
    GB: columnHelper.accessor("GB", columnHelperProperties),
    LD: columnHelper.accessor("LD", columnHelperProperties),
    FB: columnHelper.accessor("FB", columnHelperProperties),
    PU: columnHelper.accessor("PU", columnHelperProperties),
    SB: columnHelper.accessor("SB", columnHelperProperties),
    CS: columnHelper.accessor("CS", columnHelperProperties),
    AVG: columnHelper.accessor("AVG", columnHelperProperties),
    OBP: columnHelper.accessor("OBP", columnHelperProperties),
    SLG: columnHelper.accessor("SLG", columnHelperProperties),
    OPS: columnHelper.accessor("OPS", columnHelperProperties),
    ISO: columnHelper.accessor("ISO", columnHelperProperties),
    BABIP: columnHelper.accessor("BABIP", columnHelperProperties),
    "BB%": columnHelper.accessor("BB%", columnHelperProperties),
    "K%": columnHelper.accessor("K%", columnHelperProperties),
    "K/BB": columnHelper.accessor("K/BB", columnHelperProperties),
    wOBA: columnHelper.accessor("wOBA", columnHelperProperties),
    wRAA: columnHelper.accessor("wRAA", columnHelperProperties),
    wRC: columnHelper.accessor("wRC", columnHelperProperties),
    "wRC+": columnHelper.accessor("wRC+", columnHelperProperties),
    "GB%": columnHelper.accessor("GB%", columnHelperProperties),
    "LD%": columnHelper.accessor("LD%", columnHelperProperties),
    "FB%": columnHelper.accessor("FB%", columnHelperProperties),
    "PU%": columnHelper.accessor("PU%", columnHelperProperties),
};
